import Head from 'next/head'
import BlogPosts from '../components/BlogPosts'
import Container from '@material-ui/core/Container'
import SubmitBlogPostForm from '../components/SubmitBlogPostForm'
import { useMutation } from '@apollo/client'
import { ADD_POST } from '../graphql/queries'


export default function Home() {


  const [addBlogPost] = useMutation(ADD_POST,{
    onCompleted: (data) => {
      window.location.reload();
    }
  });

  const onSubmit = (e) => {
    e.preventDefault()
    addBlogPost({ variables:{ text: e.target.text.value}})
  }

  return (
    <Container maxWidth="xs">
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />

      </Head>

      <SubmitBlogPostForm onSubmit={onSubmit}/>
      <BlogPosts/>
     
    </Container>
  )
}
