import Head from 'next/head'
import BlogPosts from '../components/BlogPosts'
import Container from '@material-ui/core/Container'
import SubmitBlogPostForm from '../components/SubmitBlogPostForm'
import { useMutation } from '@apollo/client'
import { ADD_POST, DELETE_BLOGPOST, EDIT_BLOGPOST } from '../graphql/queries'
import EditModal from '../components/EditModal'
import { useState } from 'react'


export default function Home() {

  const [isEditId, setIsEditID ] = useState("");

  const onClose = () => setIsEditID("");

  const openModal = (id) => setIsEditID(id)

  const [addBlogPost] = useMutation(ADD_POST,{
    onCompleted: (data) => {
      window.location.reload();
    }
  });

  const [deleteBlogPost] = useMutation(DELETE_BLOGPOST, {
    onCompleted: (data) => {
      window.location.reload();
    }
  })


  const [editBlogPost] = useMutation(EDIT_BLOGPOST, {
    onCompleted: (data)=>{
      setIsEditID("")
    }
  });


  const onSave = (e) => {
    e.preventDefault();
    editBlogPost({ variables:{id: isEditId,  text:e.target.text.value}});
  }

  const onSubmit = (e) => {
    e.preventDefault()
    addBlogPost({ variables:{ text: e.target.text.value}})
  }

  const onDelete = (id) => deleteBlogPost({ variables: { id}})


  return (
    <Container maxWidth="xs">
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />

      </Head> 

      <EditModal isOpen={!!isEditId} onClose={onClose} onSubmit={onSave}/>
      <SubmitBlogPostForm onSubmit={onSubmit}/>
      <BlogPosts onDelete={onDelete} openModal={openModal}/>
     
    </Container>
  )
}
